create type tipo_medio as enum (
	'pelicula',
	'musical',
	'drama'
);

create type tipo_metraje as enum (
	'cortometraje',
	'mediometraje',
	'largometraje'
);

create type tipo_estilo as enum (
	'webtoon',
	'cómic',
	'manga',
	'otro'
);

create type tipo_tipo as enum (
	'Independiente',
	'Comercial'
);

create type tipo_coleccion as enum (
	'serie',
	'saga-bilogía',
	'saga-trilogía',
	'saga-tetralogía',
	'saga-pentalogía',
	'saga-hexalogía',
	'saga-heptalogía',
	'saga-octalogía',
	'otro'
);

create type tipo_idioma as enum (
	'Acadio', 
	'Afrikáans', 
	'Aimara', 
	'Albanés', 
	'Alemán', 
	'Amárico', 
	'Árabe', 
	'Armenio', 
	'Avéstico', 
	'Bengalí', 
	'Bielorruso', 
	'Bretón', 
	'Búlgaro', 
	'Catalán', 
	'Checo', 
	'Cheroqui', 
	'Chino cantonés', 
	'Chino mandarín', 
	'Copto', 
	'Coreano', 
	'Croata', 
	'Danés', 
	'Eslavo eclesiástico', 
	'Eslovaco', 
	'Esloveno', 
	'Español', 
	'Estonio', 
	'Euskera', 
	'Filipino (tagalog)', 
	'Finlandés', 
	'Francés', 
	'Gaélico escocés', 
	'Gallego', 
	'Georgiano', 
	'Griego', 
	'Griego clásico', 
	'Guaraní', 
	'Guyaratí', 
	'Hausa', 
	'Hawaiano', 
	'Hebreo', 
	'Hindi', 
	'Húngaro', 
	'Igbo', 
	'Indonesio', 
	'Inglés', 
	'Inuit', 
	'Irlandés', 
	'Islandés', 
	'Italiano', 
	'Japonés', 
	'Kurdo', 
	'Latín', 
	'Letón', 
	'ASL',
	'BSL',
	'LSF',
	'LSM',
	'LSE', 
	'Lituano', 
	'Luxemburgués', 
	'Malayo', 
	'Maorí', 
	'Mapudungun', 
	'Maratí', 
	'Maya yucateco', 
	'Mongol', 
	'Náhuatl', 
	'Navajo', 
	'Neerlandés', 
	'Nepalí', 
	'Noruego', 
	'Occitano', 
	'Pali', 
	'Persa (farsi)', 
	'Polaco', 
	'Portugués', 
	'Punyabí', 
	'Quechua', 
	'Rumano', 
	'Ruso', 
	'Sami', 
	'Sánscrito', 
	'Serbio', 
	'Somali', 
	'Suajili', 
	'Sueco', 
	'Sumerio', 
	'Tailandés', 
	'Tamil', 
	'Telugu', 
	'Tibetano', 
	'Turco', 
	'Ucraniano', 
	'Urdu', 
	'Vietnamita', 
	'Yoruba', 
	'Zulú'
);

create type tipo_pais as enum (
	'Desconocido',
	'Afganistán',
	'Albania',
	'Alemania',
	'Andorra',
	'Angola',
	'Antigua y Barbuda',
	'Arabia Saudita',
	'Argelia',
	'Argentina',
	'Armenia',
	'Australia',
	'Austria',
	'Azerbaiyán',
	'Bahamas',
	'Bangladés',
	'Barbados',
	'Baréin',
	'Bélgica',
	'Belice',
	'Benín',
	'Bielorrusia',
	'Birmania (Myanmar)',
	'Bolivia',
	'Bosnia y Herzegovina',
	'Botsuana',
	'Brasil',
	'Brunéi',
	'Bulgaria',
	'Burkina Faso',
	'Burundi',
	'Bután',
	'Cabo Verde',
	'Camboya',
	'Camerún',
	'Canadá',
	'Catar',
	'Chad',
	'Chile',
	'China',
	'Chipre',
	'Ciudad del Vaticano',
	'Colombia',
	'Comoras',
	'Corea del Norte',
	'Corea del Sur',
	'Costa de Marfil',
	'Costa Rica',
	'Croacia',
	'Cuba',
	'Dinamarca',
	'Dominica',
	'Ecuador',
	'Egipto',
	'El Salvador',
	'Emiratos Árabes Unidos',
	'Eritrea',
	'Eslovaquia',
	'Eslovenia',
	'España',
	'Estados Unidos',
	'Estonia',
	'Esuatini (Swazilandia)',
	'Etiopía',
	'Fiji',
	'Filipinas',
	'Finlandia',
	'Francia',
	'Gabón',
	'Gambia',
	'Georgia',
	'Ghana',
	'Granada',
	'Grecia',
	'Guatemala',
	'Guinea',
	'Guinea-Bisáu',
	'Guinea Ecuatorial',
	'Guyana',
	'Haití',
	'Honduras',
	'Hungría',
	'India',
	'Indonesia',
	'Irak',
	'Irán',
	'Irlanda',
	'Islandia',
	'Islas Marshall',
	'Islas Salomón',
	'Israel',
	'Italia',
	'Jamaica',
	'Japón',
	'Jordania',
	'Kazajistán',
	'Kenia',
	'Kirguistán',
	'Kiribati',
	'Kuwait',
	'Laos',
	'Lesoto',
	'Letonia',
	'Líbano',
	'Liberia',
	'Libia',
	'Liechtenstein',
	'Lituania',
	'Luxemburgo',
	'Macedonia del Norte',
	'Madagascar',
	'Malasia',
	'Malaui',
	'Maldivas',
	'Malí',
	'Malta',
	'Marruecos',
	'Mauricio',
	'Mauritania',
	'México',
	'Micronesia',
	'Moldavia',
	'Mónaco',
	'Mongolia',
	'Montenegro',
	'Mozambique',
	'Namibia',
	'Nauru',
	'Nepal',
	'Nicaragua',
	'Níger',
	'Nigeria',
	'Noruega',
	'Nueva Zelanda',
	'Omán',
	'Países Bajos',
	'Pakistán',
	'Palaos',
	'Palestina',
	'Panamá',
	'Papúa Nueva Guinea',
	'Paraguay',
	'Perú',
	'Polonia',
	'Portugal',
	'Reino Unido',
	'República Centroafricana',
	'República Checa',
	'República del Congo',
	'República Democrática del Congo',
	'República Dominicana',
	'Ruanda',
	'Rumanía',
	'Rusia',
	'Samoa',
	'San Cristóbal y Nieves',
	'San Marino',
	'San Vicente y las Granadinas',
	'Santa Lucía',
	'Santo Tomé y Príncipe',
	'Senegal',
	'Serbia',
	'Seychelles',
	'Sierra Leona',
	'Singapur',
	'Siria',
	'Somalia',
	'Sri Lanka',
	'Sudáfrica',
	'Sudán',
	'Sudán del Sur',
	'Suecia',
	'Suiza',
	'Surinam',
	'Tailandia',
	'Taiwán',
	'Tanzania',
	'Tayikistán',
	'Timor Oriental',
	'Togo',
	'Tonga',
	'Trinidad y Tobago',
	'Túnez',
	'Turkmenistán',
	'Turquía',
	'Tuvalu',
	'Ucrania',
	'Uganda',
	'Uruguay',
	'Uzbekistán',
	'Vanuatu',
	'Venezuela',
	'Vietnam',
	'Yemen',
	'Zambia',
	'Zimbabue'
);

create  table vampcat (
	id_vampcat integer primary key
);

create table usuario (
	id_usuario integer primary key,
	nombre varchar(50) not null,
	id_vampcat integer references vampcat(id_vampcat)
);

/*create table libro (
	id_libro integer primary key,
	png varchar(500) null,
	pais tipo_pais not null,
 	titulo varchar(200) not null,
	autor varchar(200) not null,
	editorial varchar(200) null,
	idioma tipo_idioma not null,
	anio_publicacion integer null,
	coleccion tipo_coleccion not null,
	genero text not null,
	personaje text not null,
  	resumen text not null,
	valoracion integer not null,
	detalles text null,
	id_vampcat integer references vampcat(id_vampcat)
);*/

create table libro (
	id_libro serial primary key,
	png varchar(500) null,
	pais tipo_pais not null,
 	titulo varchar(200) not null,
	autor varchar(200) not null,
	editorial varchar(200) null,
	idioma tipo_idioma not null,
	anio_publicacion integer null,
	coleccion tipo_coleccion not null,
	genero text not null,
	personaje text not null,
  	resumen text not null,
	valoracion integer not null,
	detalles text null,
	id_vampcat integer references vampcat(id_vampcat)
);

create table novela_grafica (
	id_novela integer primary key,
	png varchar(500) null,
	pais tipo_pais not null,
	titulo varchar(200) not null,
	autor varchar(200) not null,
	editorial varchar(200) null,
	idioma tipo_idioma not null,
	anio_publicacion integer null,
	coleccion tipo_coleccion not null,
	genero_demografia text not null,
	tipo tipo_tipo not null,
	dibujo text null,
	estilo tipo_estilo not null,
	personaje text null,
	resumen text not null,
	valoracion integer not null,
	detalles text null,
	id_vampcat integer references vampcat(id_vampcat)
);

create table obra (
	id_obra integer primary key,
	png varchar(500) null,
	pais tipo_pais not null,
	titulo varchar(200) not null,
	director varchar(200) not null,
	guionista varchar(200) null,
	editorial varchar(200) null,
	anio_estreno integer null,
	duracion integer null,
	genero text not null,
	argumento text not null,
	idioma tipo_idioma not null,
	url text null,
	reparto text null,
	metraje tipo_metraje not null,
	medio tipo_medio not null,
	valoracion integer not null,
	detalles text null,
	id_vampcat integer references vampcat(id_vampcat)
);

create table anime (
	id_anime integer primary key,
  	png varchar(500) null,
	pais tipo_pais not null,
	titulo_romaji varchar(200) null,
	titulo_english varchar(200) not null,
	mangaka text not null,
	formato integer not null,
	estudio_animacion varchar(200) not null,
	idioma tipo_idioma not null,
	url text null,
	demografia text not null,
	sinopsis text not null,
	anio_emision integer null,
	personajes text null,
	valoracion integer not null,
	detalles text null,
	id_vampcat integer references vampcat(id_vampcat)
);